DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0MzI5MTU4LCJ1c2VySWQiOjJ9.QgfCVYoC0H2H-CK7hYEvY0wKjxiergpiFGuM1K6W1dE
