PUT http://localhost:8080/events/5
content-type: application/JSON
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA0MzMwNTIwLCJ1c2VySWQiOjJ9.Qpy6n4Pxb7ray66oB3O9KBsTtsfmcpIsC9QRN_kyJpQ

{
    "name": "Testing 2",
    "description": "Lorem ipsum doplur",
    "location": "New York",
    "dateTime": "2025-01-01T15:30:00.000Z"
}